on: 
  push:
    branches:
      - master
      - fadeenk-patch-1
      
name: Test and Publish

jobs:
  test:
    name: Test on  ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10, 12]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm test
  publish:
    name: Publish package
    runs-on: node:8
    steps:
    - name: Publish
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
